import poster from "../assets/poster.jpg";

export const features = [
  {
    id: 1,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 2,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 3,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 4,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 5,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 6,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 7,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 8,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 9,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 10,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 11,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
  {
    id: 12,
    poster: poster,
    year: "USA 2015",
    title: "Stranger Things",
    rating: 820,
    genre: "Action, Adventure",
  },
];
